"""empty message

Revision ID: 5c7618d34948
Revises: 4301d038561a
Create Date: 2016-12-22 09:52:40.745113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7618d34948'
down_revision = '4301d038561a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address', sa.Text(), nullable=True))
    op.drop_column('address', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('address', 'address')
    # ### end Alembic commands ###
