"""empty message

Revision ID: bd140ffe0342
Revises: 1afa024d91cb
Create Date: 2016-12-22 09:38:23.796249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd140ffe0342'
down_revision = '1afa024d91cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_dir', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_dir')
    # ### end Alembic commands ###
